---
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.59.1/hugo_0.59.1_Linux-64bit.deb
    -O hugo.deb
  - sudo dpkg -i hugo.deb
script:
  - hugo
deploy:
  provider: s3
  access_key_id: 
    secure: "Xh9UJQ5nLgyzAVW4ZiEKnyMCHOpFmoSa+ylGeah/8bLlfKb/HGC2xkSXxmEgJ1efpNl0CDN7VWn8NRkxNYtjUPxsF5CYUp3IsgO6/5fOONwMuudeG/ap48FlXmWm81xiZlkQHrMM/trvfc0s2AN0eRMHaxk9o1KQ1dNPz+QYh3jvHEJlSQYZgRROcGpzJFLuN1/QrX9xdOXUhZ0R7uMvwPoWeqHevv8jLJOSJpT/9386wAbQVU/ngXZaKkn1nYaefpNEjQQzGzyyq8U3rmD1HkSXLOvB4XksIJqoQ0QFDgREFF/x8ZRBEOcY4g9/wwWgRuPJrIqhZMN5Dz41lS/ce/G5r/aF6Rga+6MEnBCJpsh0T2mcatb18TXz1HGPV7/mqyuqvI+oJXFHBFf5jDpUY+sRFxHqOlnKSzORbtLfFarmUDwWZI7/Ef/wDvN37rnjX8bQ0DVH6kuLAsa7gaSz4UZDz4A1HdctZU+Dq4jQspWo4CeKc+arsGcQbU2zuoaiUHbcfxnFqG+twsUv75+6V2ZfuuPyOhkKBd54NcSQg8P1YqP8e1iqsWixbHziOuEIa+l2trbKYm2h3bHFsFSeBa/g7CarsTasNW3MFi0WvBPAVFN2IKohnS6AWFLXVHOBrnNJLLCPIt2QtPl0Cb241kbAXBerX+ncot/wR71c6Jk=" 
  secret_access_key:
    secure: "BmlRC5K6y943x9Q84WKZgJX2JUqvch8hS6njTSKo9+azBBgAdpBAgLeKjO/yBN+lcX5LWUbp9cTaaw5Dy3zhNBmjc5SlEvK2s5Uu61XO24+V48J76d+efc2PfjdWTu6lT6cFsqfhdoLRtdauW0bQLQwyy4HvMBXc4zi4ZaivymGbNMeFlIgFNwaqYWGWYS5Y9iqe0ueLZwWPZJp2hfby0GZ0/ufc0W8Ti47smrRbGVxhxDyJmH3Wzyma3G44hl1OwhmZoth3LrmKaqPgw5fDpxTM99QfzeilgnmOgXf0Cv9/Tc+KZbzXKEkjYennigCcmmsUBjd85gEp4RnPYdUq7J8HVLmiC9wUuBV535E8TQym1KBox4tBAxLfr5XHrGyR5nJbMiXWlO6jWb+LO/LOulQ1jWVBbkzh5fCc/N1qhtGmNCiINq9Ftj66snNsTr9kyQkNK9ryoAT5VhXhKdzKMUXCSkecL07LHopziSJOHeohUJ0uUAnZj8HnctzTX5SudytsglobbunhBV1sQr4TAwdWPrOmWvPOzxwyssgkuPiZ/P09fHUaHVfIr5/auqsJhppGvHc8Cv9E5MjbtmhOu91FHtgHurbpG1KBnFoRHMmChxWHTTnN9KQsG7G96i1tdghcMlicrReZQ5cateJ9CCVCZhMMQjV55FXLm/0i6Lg="
  bucket: www.thaniri.com
  region: us-east-1
  local_dir: public
