---
env:
  global:
  - secure: sI3Fh9pdV2q04Ddi/HONqCvgok47KETQmg47Q0T/1X95uI3ZyXg1CrDR/4bM78oAoEZLzZjdmUaGTztSpybtjoTZVP5XHoi60MT/gd8Hp11B19KaMpmphf8QzGy1qRbfh0vV7popqF72JvFhI7Gv9p8Uo5TRLZDOcGt2befXjKB2KwktfovIvGTy1ZRoXRiNNyEmZgN5Qaq0J+nfPzN5/mAVc/7vlHGYXX83fnstYqKshyVJ6/womiQPuXsyfxNu0xbcuIUglXVz4FTC+s9bwN0PQYyYSS3HVdS442gFdPEpXZXuke5aRyEoUf8zRPr3sL6FVlJ2663pCxLkf6Hox/k+8ULMoj1oarR64duBHTANIlNzW0C0xOrEEQg1CZ/LXwhdO4j7DO2qf1fR/qGgKYceGTmzh+Ag6GOctKorOqsguBqaXpBg8+USeuYVeg4DzWznjPpgvu+WLnydyPCJywJZLMXxjpBWmr4fElcMY2PkHi6vRd0ehFx5aVwF0nwRthYvypihYDxRV1oApcpOvOwvq/23AR4x5I3ZHpNpe7Qym59pKjjuYZ3jN0Wop02efvUjWi7BdUXElfyrX2WcD2iVKmWoHfAWOp7IJmmWrEMdyhjB/T87cRyv2/zOMXSyLHnFQ+fccTTq3kciGVYgFbD3jzCRZB22xbrbUSe0Nwk=
  - secure: H565B4VPJeH5ES6xZwuhQ2HP3b0IGcOuYuREb/4OX8A64WBXQ/TKneSBjyA61CV0l/DQK0uz8SXad1QYYidY6Uo7U46EaSW70fK0t27ic0vczpyJYwMxibaQOkhDL7IZG+9xdl3VpTzBRku8Bc6y6ZbEEgeph0nImnAXqkwgPNTeQQt/mXNBLkjAOUIKveD11mHtDTONwzLHrTqg4Di2slLwRuXWuh+j6JL+eY9IpJeFfgDYrCvAiZGoYQk/53g4QziYFPioC6kTQ6gap/z/OZxOZxQ2phZ0XVQgVAkpHqx53WTt2SvJFi2Qcj72twSjIMedhTPGNYG/83FOsNhWBwjUkCZQsJLssqpkrNUvdmQrBaSOPEErBS5aqYhaV0x2zZfXCH7tvmn9IOrYZt1P+b6jDx/25U7of2jb27LYIKCXkLVXZJPgk323p7GiNdTpBt4SlSamT/KPtvlT38ueaVmWbgDjBF+l1p7fTYGWQaG58fTFiOGbyDx3ceowczC9RKNOWFBz8VBtZYVyNMthXVUpDKG9NG/2ao8U99W/N4qlcaIcKfPQekmwfDRFKraPlgUEYQ6dRstWFYXKIzogLfvBOtgpSbB7dwB3zQDRn7yMZerD7KlpZiQ1QG9ofzBWknNuIVuFYTM4GM0QH1ieb0V6/MSs2oB3Kb2XZ8BW4zk=
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.59.1/hugo_0.59.1_Linux-64bit.deb -O hugo.deb
  - sudo dpkg -i hugo.deb
script:
  - hugo
deploy:
  provider: s3
  access_key_id: $KEY_ID
  secret_access_key: $ACCESS_KEY
  bucket: www.thaniri.com
  region: us-east-1
  local_dir: public
