install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.59.1/hugo_0.59.1_Linux-64bit.deb
  -O hugo.deb
- sudo dpkg -i hugo.deb
script:
- hugo
deploy:
  provider: s3
  access_key_id: AKIAJLKMABGCOXGLQKWA
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: www.thaniri.com
  local-dir: public
  skip_cleanup: true
  region: us-east-1
