install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.59.1/hugo_0.59.1_Linux-64bit.deb
  -O hugo.deb
- sudo dpkg -i hugo.deb
script:
- hugo
deploy:
  provider: s3
  access_key_id: "$KEY_ID"
  secret_access_key: "$ACCESS_KEY"
  bucket: www.thaniri.com
  region: us-east-1
  local_dir: public
env:
  global:
  - secure: IfqyAcsAe9nKlUXT0HesGCic8Y/7YH+ikYOdD1FhCINOQnvk8kPSUlf1uB7XTok2iCd6Cq+EBSq2XPmLwHrS4VeH7sUj0si1wIkVJxOfDEZglXEN8ex5cYnp0xh6TtLcB/a55aw9UMs8SZjJMNdf8AtIOp+AKVr9oyuKp3/ihxhKI1iEpT9jiHeUZIsHgi8lhYKOT6yZfXV2UHptgtAE8yDLj6KRARk4pcPMmGuxq7RzEWCfxZTdq/YU7HIe8JjRVr+DcMkTo3fNSAV73J6cohoQvvB0BWTwIC8FY3NOhyJD6TyTxFRvhTM1/5wbp1DJFTvqgILxDc0uC7dCycLElm5WOXfwft8vpmGF/1r0SorPwVeE7K+A5YF6QSHkNJaaU9mDHB58xbqpZMZudCzyTW9mWYO2/2J4apJaB2OMbkOje2v+WKAfv9dJ9uXzQK4WXr4asMsj9YVlVC8Jz0GWxDUg+QNIDXVquHN7kfiKhJDDUGZiBSpDvi8sDEdsxrIbr6BrRpJsnV6Xer+KgJJSPrOtg0CF2ZCwvnBl55VG3B4b1BvZBANO3mmR0R+Bqp48aydI/CwTExfl1Wqoy5RmUrZujbOqGvgmtp2VbcXLpAMShpIa0v3YrD1P0TjODG6OZOsaX/B0Q6ts57b3xTVU6CR14qKhGDG8iB4xbIKYG1E=
  - secure: VTi5dSfWMnLfKNuAHcxKV5F+j0RRvFHoB80b/MisV4uX5hmcBQJl6ahJDNLQG36n6C1Wx331SSJbcpURpUjeVQ2u5PaOBhlimPf+LwXn2tS0YfdLGoGG8m/c+4mT0Vwd0qN4Tc8PTa55dxwIMXq44A931JcU3YVj+ClWWt9k2K/4m3kufRJcoNa3/2PgODUAEirYRd1nxpp5DtK67+q5HrtyRAHtvCmgc6fq1jLdYWnzwOwIrAOUX1ZzemlOe6EGESM40AqEDrIrLsIp4Pw7dbRNIbgZHWOth1d5ZMKLoe54vIm7hG5+X6YIHrmT0HySTxTJuSuo2P46RfyHRQtCqTxvyoPpdo5WZZFkP3P9xYIqn/au9Pu/vnfhOOORxMRVj5z5ki+0IzS+5O5OyKm5KwPnQrHIq1kXCO537ma7Ix/zYALnITFfgKgJ+Zc/TvToo4ncOEH2DbTdnhJjTIvyM10d7SvlRk/0rNzFLDsdskrhNUdlwwMShieVFq05DlLG7+GkYDb3g6kTA9ypi/+zFbYpdzkMk/sx2hNxmnxlAkbvROVvxWneUY5bWv6UWZHKazW6gnQXx4P7lOr0wEvL1+aQiPCwDi+c66m0kDhJevp+BSPYU/rnROa/EsmkQymrhoAu7YRF1nLCb4XtfCFUhbe8IgL1JN32lBEtyhbKpJs=
