---
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.59.1/hugo_0.59.1_Linux-64bit.deb
    -O hugo.deb
  - sudo dpkg -i hugo.deb
script:
  - hugo
deploy:
  provider: s3
  access_key_id: $KEY_ID
  secret_access_key: $ACCESS_KEY
  bucket: www.thaniri.com
  region: us-east-1
  local_dir: public
  skip_cleanup: true
